# Generated by Django 4.2.11 on 2024-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_leader", models.BooleanField(default=False)),
                ("hearts", models.IntegerField()),
            ],
        ),
    ]
